### ISSUE TITLE
Connecting DeFi to the non-crypto audience in Web 3.0 

### ISSUE THREAD

**Issue by HeyWeiPan** [IOSGVentures/Gitcoin-x-Kickstarter#3]
📍Bounty Challenge #2
【Prize Title】
Connecting DeFi to the non-crypto audience in Web 3.0 

【Prize Bounty】
USDC：2000

【Challenge Description】

The majority of DeFi projects are targeting a crypto native audience. There are only several projects exploring ways to introduce DeFi to the mainstream public. For instance, applications allowing non-crypto users to tap into DeFi yields, or projects such as Centrifuge connecting SMEs to the DeFi liquidity. We believe DeFi is yet to capture the majority of its potential and the largest impact will be felt in reforming the traditional way of doing finance.

As a developer-friendly venture capital, IOSG believes there are world-changing entrepreneurs. The Kickstarter Program is designed to support those developers and early-stage project teams contributing to the blockchain ecosystem worldwide. We would like to see more innovative spirits and help them grow. We also welcome each hackathon participant to apply for the Kickstarter program, the shortlist project will be supported with 10-100k usd and mentorship. Hackathon winners will be fast tracked through the application process. It’s open to anyone to apply. For more info, see link below in Resources.
 

【Submission Requirements】

The following areas may be the low hanging fruits where DeFi could truly showcase its power: 
insurance industry
utilizing the power of synthetic assets to issue diverse derivative offering from a commodity to weather derivatives
money transfer/payments
replacing conventional banking services

【Judging Criteria】

The prize will be awarded to the individual/team that produces the best approach and the most user-friendly solution while respecting the challenge description. 

【Winner Announcement Date】
July 12, 2021 (Monday)

【Resources】
IOSG Ventures
You can follow us on Twitter/Linkedin.
Join our Telegram if you have any questions.
About Kickstarter Program

**Comment by IOSGVC** [comment]
📍Bounty Challenge #2
【Prize Title】
Connecting DeFi to the non-crypto audience in Web 3.0

【Prize Bounty】
USDC：2000

【Challenge Description】

The majority of DeFi projects are targeting a crypto native audience. There are only several projects exploring ways to introduce DeFi to the mainstream public. For instance, applications allowing non-crypto users to tap into DeFi yields, or projects such as Centrifuge connecting SMEs to the DeFi liquidity. We believe DeFi is yet to capture the majority of its potential and the largest impact will be felt in reforming the traditional way of doing finance.

As a developer-friendly venture capital, IOSG believes there are world-changing entrepreneurs. The Kickstarter Program is designed to support those developers and early-stage project teams contributing to the blockchain ecosystem worldwide. We would like to see more innovative spirits and help them grow. We also welcome each hackathon participant to apply for the Kickstarter program, the shortlist project will be supported with 10-100k usd and mentorship. Hackathon winners will be fast tracked through the application process. It’s open to anyone to apply. For more info, see link below in Resources.

【Submission Requirements】

The following areas may be the low hanging fruits where DeFi could truly showcase its power:
insurance industry
utilizing the power of synthetic assets to issue diverse derivative offering from a commodity to weather derivatives
money transfer/payments
replacing conventional banking services

【Judging Criteria】

The prize will be awarded to the individual/team that produces the best approach and the most user-friendly solution while respecting the challenge description.

【Winner Announcement Date】
July 12, 2021 (Monday)

【Resources】
[IOSG Ventures](https://iosg.vc/)
You can follow us on [Twitter](https://twitter.com/IOSGVC)/[Linkedin](https://www.linkedin.com/company/14480831/admin/).
Join our [Telegram](https://t.me/joinchat/dcYf8ZpOSJ5hNWJl) if you have any questions.
About [Kickstarter Program](https://iosg.vc/kickstarterprogram/)
